/**
 * Seed the players, the v1 ruleset, the competition catalogue, and the 2026/27
 * season.
 *
 * The season's slots are generated by running the workbook's own 2026/27 row
 * labels through the same mapper the importer uses, so the app asks for exactly
 * the predictions the sheet would have. Idempotent — safe to re-run.
 */

import { readFileSync } from "node:fs";
import { prisma, applyPragmas } from "@/lib/db";
import { COMPETITIONS, EUROPEAN_CUP_KEYS } from "@/lib/competitions";
import { SEED_ALIASES } from "@/lib/aliases";
import { normalise } from "@/lib/teams";
import { mapRow, newMapperState } from "@/lib/import/slotMapping";
import {
  CHAMPIONSHIP_OVERRIDES,
  EUROPEAN_CUP_OVERRIDES,
  LEAGUE_RULESET_V1,
} from "@/lib/scoring/ruleset";

const PLAYERS = [
  { handle: "KV", displayName: "King Voj", isAdmin: false },
  { handle: "MC", displayName: "MC", isAdmin: false },
  { handle: "Tok", displayName: "Tok", isAdmin: true },
];

const SEASON_LABEL = "2026/27";
const SEASON_SHEET = "202627";

function overridesFor(key: string): string | null {
  if (EUROPEAN_CUP_KEYS.includes(key)) return JSON.stringify(EUROPEAN_CUP_OVERRIDES);
  if (key === "championship") return JSON.stringify(CHAMPIONSHIP_OVERRIDES);
  return null;
}

async function main() {
  await applyPragmas();

  for (const p of PLAYERS) {
    await prisma.player.upsert({
      where: { handle: p.handle },
      update: { displayName: p.displayName, isAdmin: p.isAdmin },
      create: p,
    });
  }
  console.log(`players: ${PLAYERS.length}`);

  const ruleset = await prisma.ruleset.upsert({
    where: { key: "league-v1" },
    update: { config: JSON.stringify(LEAGUE_RULESET_V1) },
    create: {
      key: "league-v1",
      name: "League scoring v1",
      config: JSON.stringify(LEAGUE_RULESET_V1),
      notes:
        "Transcribed from the season sheets' Points block and verified against " +
        "2025/26. Do not edit — new scoring means a new ruleset row.",
    },
  });

  for (const c of COMPETITIONS) {
    await prisma.competition.upsert({
      where: { key: c.key },
      update: { name: c.name, country: c.country, kind: c.kind, providerCode: c.providerCode },
      create: c,
    });
  }
  console.log(`competitions: ${COMPETITIONS.length}`);

  for (const { alias, canonical } of SEED_ALIASES) {
    const team = await prisma.team.upsert({
      where: { name: canonical },
      update: {},
      create: { name: canonical },
    });
    // Store the normalised form so rows match how the lookup index is keyed
    // ("Paris Saint-Germain" -> "paris saint germain", not "paris saint-germain").
    await prisma.teamAlias.upsert({
      where: { alias: normalise(alias) },
      update: { teamId: team.id },
      create: { alias: normalise(alias), teamId: team.id },
    });
  }
  console.log(`team aliases: ${SEED_ALIASES.length}`);

  // The change window: January of the season's second calendar year.
  const season = await prisma.season.upsert({
    where: { label: SEASON_LABEL },
    update: {},
    create: {
      label: SEASON_LABEL,
      startYear: 2026,
      kind: "LEAGUE",
      rulesetId: ruleset.id,
      isActive: true,
      changeBudget: 3,
      changeWindowStart: new Date("2027-01-01T00:00:00Z"),
      changeWindowEnd: new Date("2027-01-31T23:59:59Z"),
    },
  });

  const workbook = JSON.parse(readFileSync("scripts/workbook.json", "utf8")) as {
    seasons: Record<string, { rows: { label: string }[] }>;
  };

  const state = newMapperState();
  let displayOrder = 0;
  let slotCount = 0;
  const seenCompetitions = new Map<string, string>();

  for (const row of workbook.seasons[SEASON_SHEET].rows) {
    const mapped = mapRow(row.label, state);
    if (!mapped) throw new Error(`Unmapped row in ${SEASON_SHEET}: ${row.label}`);

    let seasonCompetitionId = seenCompetitions.get(mapped.competitionKey);
    if (!seasonCompetitionId) {
      const competition = await prisma.competition.findUniqueOrThrow({
        where: { key: mapped.competitionKey },
      });
      const sc = await prisma.seasonCompetition.upsert({
        where: { seasonId_competitionId: { seasonId: season.id, competitionId: competition.id } },
        update: { ruleOverrides: overridesFor(mapped.competitionKey) },
        create: {
          seasonId: season.id,
          competitionId: competition.id,
          displayOrder: seenCompetitions.size,
          ruleOverrides: overridesFor(mapped.competitionKey),
        },
      });
      seasonCompetitionId = sc.id;
      seenCompetitions.set(mapped.competitionKey, sc.id);
    }

    await prisma.slot.upsert({
      where: {
        seasonCompetitionId_kind_ordinal: {
          seasonCompetitionId,
          kind: mapped.kind,
          ordinal: mapped.ordinal,
        },
      },
      update: { label: row.label, displayOrder, valueType: mapped.valueType },
      create: {
        seasonCompetitionId,
        kind: mapped.kind,
        ordinal: mapped.ordinal,
        label: row.label,
        displayOrder,
        valueType: mapped.valueType,
      },
    });
    displayOrder += 1;
    slotCount += 1;
  }

  console.log(
    `season ${SEASON_LABEL}: ${seenCompetitions.size} competitions, ${slotCount} slots`,
  );
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
